version: '2'

services:
    server:
        build: .
        container_name: ws_server
        volumes:
            - ".:/usr/src/app"
        working_dir: "/usr/src/app"
        ports:
            - "80:8080"
            - "5858:5858"
        command: npm start
